In [144]:
#Chapter 5 HOMEWORK
import pandas as pd #importing pandas libray
pd.__version__

'3.0.2'

In [145]:
df =pd.read_csv('TITANIC.csv') # reading/ displaying titanic list
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [146]:
df.loc[0:9] # Display the dataset's first ten rows to gen an overview

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [147]:
# Determine the dataset's dimensions (number of rows and columns)
print(df.index) # understanding row indexing
print(df.columns) # We can see column names

df.shape #Standard pandas method and direct answer to the question

RangeIndex(start=0, stop=891, step=1)
Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

(891, 12)

In [148]:
# Count the number of passengers in each class (Pclass)
df['Pclass'].value_counts()

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [149]:
df.loc[df['Age'] < 1] # Locates persons who are infants. Just checking if I should include persons with 0 years
df['Age'].isnull()
no_age_data = df['Age'].dropna() # Removing all NaN from Age column
no_age_data.isnull().sum()

# Calculate the average age of passengers
avg_age = no_age_data.mean()
print("The average age is", round(avg_age,2))

The average age is 29.7

In [150]:
# What this method does

df.describe()

# 1. Count - Returns number of non-missing (NaN) values. Important: tells you about missing data.
# 2. Mean - Average value. For example average age among passengers 29.7 years
# 3. std - standard deviation. How spread out the data is. Low std means data is tightly grouped. High std data is spread out.
# Group A (low std) - [28,29,30,31,32] values are very close to each other.
# Group B (high std) - [5.15,30,50,80] values are spread out. In titanic example std is 14 which means that ages vary a lot. Have babies nad elderly people
# 4. min - Smallest value (youngest passenger, cheapest fare in this case)
# 5. 25% - first quartile 25% of data is below this value
# 6. 50% (median) - Middle value (not average) Example [10,20,30,40,50] Median = middle number is 30
# 7. 75% - third quartile 75% of data is below this value. Helps understand upper range
# 8. max - Largest value (oldest passenger or highest ticket price)

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [151]:
# Identify the oldest and youngest passangers by name
youngest = df['Age'].min() # youngest is just a number we extract from data frame
oldest = df['Age'].max()

youngest_passengers = df[df['Age'] == youngest]['Name']
# df['Age'] == youngest in background creates [False, False, True, False] asking is this row's Age equal to the youngest age?
# df[df'Age']== youngest] keeps only rows where the conditions are true. We get only rows where Age == youngest
# df[df['Age] == youngest]['Name'] from those filtered rows take only "Name" column
oldest_passangers = df[df['Age'] == oldest]['Name']


print("Youngest passenger(s):")
print(youngest_passengers)

print("\nOldest passenger(s):")
print(oldest_passangers)

Youngest passenger(s):
803    Thomas, Master. Assad Alexander
Name: Name, dtype: str

Oldest passenger(s):
630    Barkworth, Mr. Algernon Henry Wilson
Name: Name, dtype: str

In [152]:
# Determine how many passangers survived and how many perished
survived = 1
died = 0

survived_passengers = df[df['Survived'] == survived]
died_passengers = df[df['Survived'] == died]

print(f"Total of passangers who survived: {len(survived_passengers)}")
print(f"Total of passangers who died: {len(died_passengers)}")

Total of passangers who survived: 342
Total of passangers who died: 549

In [153]:
# Count the number of male and female passengers aboard the Titanic

male = "male"
female = "female"

male_on_board = df[df['Sex'] == male]
female_on_board = df[df['Sex'] == female]

print(f"Titanic had {len(male_on_board)} male passangers")
print(f"Titanic had {len(female_on_board)} female passangers")

df['Sex'].value_counts() # More panda way to do the same task. One line vs few lines above

Titanic had 577 male passangers
Titanic had 314 female passangers

Sex
male      577
female    314
Name: count, dtype: int64

In [ ]:
# How many man and women survived

# With below line from the dataframe keep only rows where sex is male and survived is 1
survived_men = df[(df['Sex'] == 'male') & (df['Survived'] == 1)]
survived_female = df[(df['Sex'] == 'female') & (df['Survived'] == 1)]

print(f"Out of all survivors {len(survived_men)} were men")
print(f"Out of all survivors {len(survived_female)} were women")

Out of all survivors 109 were men
Out of all survivors 233 were women

In [164]:
# What's the survival rate by class? 

# df['Pclass] == 3 filters class 3
# ['Survived'] take survival column
# .mean() average of 0/1 = survival rate

rate_3 = df[df['Pclass'] == 3]['Survived'].mean()
print(f"Survival rate among 3rd class is {round(rate_3,2)}")

# Better solution below
all_rates = df.groupby('Pclass')['Survived'].mean()
print(f"Survival rate: {round(all_rates,2)}")

Survival rate among 3rd class is 0.24
Survival rate: Pclass
1    0.63
2    0.47
3    0.24
Name: Survived, dtype: float64

In [ ]:
# Add a new 'FamilySize' column that sums the 'SibSp' (number of siblings/spouses aboard) and 'Parch' (number of parents/ children aboard) columns
df['FamilySize'] = df['SibSp'] + df['Parch']
df

In [171]:
# Identify the non-survivor with the most significant family on board

non_survivors = df[df['Survived'] ==0]
max_family_size = non_survivors['FamilySize'].max()
result = non_survivors[non_survivors['FamilySize'] == max_family_size]

print(result['Name'])

159           Sage, Master. Thomas Henry
180         Sage, Miss. Constance Gladys
201                  Sage, Mr. Frederick
324             Sage, Mr. George John Jr
792              Sage, Miss. Stella Anna
846             Sage, Mr. Douglas Bullen
863    Sage, Miss. Dorothy Edith "Dolly"
Name: Name, dtype: str